version: '3.8'
services:
  jira_app:
    build: .
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./shared_volume:/shared
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - JIRA_INSTANCE=${JIRA_INSTANCE}
    networks:
      - jira_network
networks:
  jira_network:
    driver: bridge
